[package]
name = "rc_event_queue"
authors = ["Andrey Diduh <tower120@gmail.com>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2018"

[dependencies]
parking_lot = "0.11.2"
spin = "0.9.2"

[dev-dependencies]
itertools = "0.10.1"
criterion = "0.3.3"

[target.'cfg(loom)'.dependencies]
loom = "0.5.1"

[[bench]]
name = "read_bench"
harness = false

[[bench]]
name = "write_bench"
harness = false

[[bench]]
name = "read_write_bench"
harness = false