[package]
name = "events"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
itertools = "0.10.1"
criterion = "0.3.3"

[[bench]]
name = "read_bench"
harness = false