name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: RUSTFLAGS="--deny warnings" cargo build

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --all-features

  benches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build benches
      run: cargo build --benches

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build doc
      run: cargo doc --lib

  loom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run loom tests
      run: RUSTFLAGS="--cfg loom" cargo test --lib tests::loom_test --release
