name: Loom tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run loom tests
      run: RUSTFLAGS="--cfg loom" cargo test --lib tests::loom_test --release
